export const homepagedata = [
  {
    products: [
      {
        id: 1,
        name: "mobiles",
      },
      {
        id: 2,
        name: "laptops",
      },
      {
        id: 3,
        name: "headphones",
      },
      {
        id: 4,
        name: "mens_tshirts",
      },
      
      {
        id: 5,
        name: "mens_shirts",
      },
      {
        id: 6,
        name: "tv",
      },
      {
        id: 7,
        name: "furnitures",
      },
      {
        id: 8,
        name: "watches",
      },
    ],
  },
];

export const mainjson = [
  {
    id: 1,
    brand: "Study Table",
    model: "",
    category: "Furnitures",
    price: 199,
    image:
      "//www.ikea.com/in/en/images/products/utespelare-gaming-desk-black__0997777_pe822755_s5.jpg?f=xxs",
    ratings: 4.5,
    delivery_time: 7,
    seller: "Ikea"
  },
  {
    id: 4,
    brand: "Wayfair",
    category: "Furnitures",
    model: "Dining Table Set",
    price: 499,
    image:
      "https://www.ikea.com/in/en/images/products/skogsta-nordviken-table-and-6-chairs-acacia-black__1097281_pe864868_s5.jpg?f=xxs",
    ratings: 4.6,
    delivery_time: 12,
    seller: "Reliance Trends"
  },
  {
    id: 5,
    brand: "La-Z-Boy",
    category: "Furnitures",
    model: "Recliner Chair",
    price: 399,
    image:
      "https://www.ikea.com/in/en/images/products/muren-recliner-remmarn-dark-grey__0908537_pe783270_s5.jpg?f=xxs",
    ratings: 4.9,
    delivery_time: 15,
    seller: "RoyalOak"
  },
  {
    id: 6,
    brand: "Serta",
    category: "Furnitures",
    model: "Pillow",
    price: 89,
    image:
      "https://www.ikea.com/in/en/images/products/rumsmalva-ergonomic-pillow-side-back-sleeper__0778781_pe759130_s5.jpg?f=xxs",
    ratings: 4.8,
    delivery_time: 10,
    seller: "Ikea"
  },
  {
    id: 7,
    brand: "Haverty's",
    category: "Furnitures",
    model: "Coffee Table",
    price: 3250,
    image:
      "https://www.ikea.com/in/en/images/products/vittsjoe-coffee-table-black-brown-glass__0836655_pe601386_s5.jpg?f=xxs",
    ratings: 4.5,
    delivery_time: 8,
    seller: "Reliance Trends"
  },
  {
    id: 8,
    brand: "West Elm",
    category: "Furnitures",
    model: "Mid-Century Sofa",
    price: 1399,
    image:
      "https://www.ikea.com/in/en/images/products/friheten-three-seat-sofa-bed-skiftebo-dark-grey__0829149_pe644867_s5.jpg?f=xxs",
    ratings: 4.7,
    delivery_time: 14,
    seller: "RoyalOak"
  },
  {
    id: 9,
    brand: "Ashley",
    category: "Furnitures",
    model: "Accent Chair",
    price: 299,
    image:
      "https://www.ikea.com/in/en/images/products/poaeng-rocking-chair-white-stained-oak-veneer-knisa-light-beige__0682937_pe720616_s5.jpg?f=xxsh",
    ratings: 4.6,
    delivery_time: 5,
    seller: "Ikea"
  },
  {
    id: 10,
    brand: "Pottery Barn",
    category: "Furnitures",
    model: "Farmhouse Dining Table",
    price: 9879,
    image:
      "https://www.ikea.com/in/en/images/products/malm-bed-frame-high-w-4-storage-boxes-black-brown-luroey__1101552_pe866728_s5.jpg?f=xxs",
    ratings: 4.7,
    delivery_time: 14,
    seller: "Reliance Trends"
  },
  {
    id: 2,
    brand: "Ashley",
    category: "Furnitures",
    model: "Sofa Sectional",
    price: 99,
    image:
      "https://www.ikea.com/in/en/images/products/soederhamn-corner-section-viarp-beige-brown__0802788_pe768596_s5.jpg?f=xxs",
    ratings: 4.8,
    delivery_time: 10,
    seller: "RoyalOak"
  },
  {
    id: 3,
    brand: "Sauder",
    category: "Furnitures",
    model: "Computer Desk",
    price: 1200,
    image:
      "https://www.ikea.com/in/en/images/products/skogsta-dining-table-acacia-black__1342684_pe949087_s5.jpg?f=xxs",
    ratings: 4.8,
    delivery_time: 12,
    seller: "Ikea"
  },
  {
    id: 11,
    brand: "CB2",
    category: "Furnitures",
    model: "Sleek Console Table",
    price: 1499,
    image:
      "https://www.ikea.com/in/en/images/products/kallax-shelving-unit-with-4-inserts-white__1051352_pe845167_s5.jpg?f=xxs",
    ratings: 4.4,
    delivery_time: 6,
    seller: "Reliance Trends"
  },
  {
    id: 12,
    brand: "Crate & Barrel",
    category: "Furnitures",
    model: "Lounge Chair",
    price: 659,
    image:
      "https://www.ikea.com/in/en/images/products/vessla-storage-crate-with-castors-light-pink__0876850_pe649299_s5.jpg?f=xxs",
    ratings: 4.6,
    delivery_time: 7,
    seller: "RoyalOak"
  },


    {
      id: 13,
      brand: "Sony",
      model: "WH-1000XM5",
      category: "Headphones",
      price: 399,
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1yYJ1mUWdicmWFw70ZA_z9Bt3pCe5rTzGTA&s",
      ratings: 4.8,
      delivery_time: 3,
      seller: "Chroma"
    },
    {
      id: 14,
      brand: "Bose",
      category: "Headphones",
      model: "QuietComfort 45",
      price: 329,
      image:
        "https://assets.bose.com/content/dam/cloudassets/Bose_DAM/Web/consumer_electronics/global/products/headphones/QCUH-HEADPHONEARN/product_silo_images/AEM_PDP_GALLERY_WHITE-1.png/_jcr_content/renditions/cq5dam.web.320.320.png",
      ratings: 4.7,
      delivery_time: 4,
      seller: "Reliance"
    },
    {
      id: 15,
      brand: "Apple",
      category: "Headphones",
      model: "AirPods Max",
      price: 549,
      image: "",
      ratings: 4.6,
      delivery_time: 5,
      seller: "MindSets"
    },
    {
      id: 16,
      category: "Headphones",
      brand: "Sennheiser",
      model: "Momentum 4",
      price: 349,
      image: "",
      ratings: 4.7,
      delivery_time: 3,
      seller: "Chroma"
    },
    {
      id: 17,
      category: "Headphones",
      brand: "Jabra",
      model: "Elite 85h",
      price: 249,
      image: "",
      ratings: 4.5,
      delivery_time: 4,
      seller: "Reliance"
    },
    {
      id: 18,
      category: "Headphones",
      brand: "Anker",
      model: "Soundcore Life Q30",
      price: 99,
      image: "",
      ratings: 4.5,
      delivery_time: 5,
      seller: "MindSets"
    },
    {
      id: 19,
      category: "Headphones",
      brand: "Beats",
      model: "Solo Pro",
      price: 299,
      image: "",
      ratings: 4.6,
      delivery_time: 3,
      seller: "Chroma"
    },
    {
      id: 20,
      category: "Headphones",
      brand: "Beyerdynamic",
      model: "DT 770 Pro",
      price: 159,
      image: "",
      ratings: 4.7,
      delivery_time: 4,
      seller: "Reliance"
    },
    {
      id: 21,
      category: "Headphones",
      brand: "Audio-Technica",
      model: "ATH-M50x",
      price: 149,
      image: "",
      ratings: 4.6,
      delivery_time: 5,
      seller: "MindSets"
    },
    {
      id: 22,
      category: "Headphones",
      brand: "Samsung",
      model: "Galaxy Buds Pro",
      price: 199,
      image: "",
      ratings: 4.5,
      delivery_time: 3,
      seller: "Chroma"
    },
    {
      id: 23,
      category: "Headphones",
      brand: "Google",
      model: "Pixel Buds A-Series",
      price: 99,
      image: "",
      ratings: 4.4,
      delivery_time: 4,
      seller: "Reliance"
    },
    {
      id: 24,
      category: "Headphones",
      brand: "OnePlus",
      model: "Buds Z2",
      price: 99,
      image: "",
      ratings: 4.3,
      delivery_time: 5,
      seller: "MindSets"
    },
  {
    id: 25,
    category: "Laptops",
    brand: "Apple",
    model: "MacBook Pro 16-inch",
    price: 2399,
    image:
      "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1698821675/Croma%20Assets/Computers%20Peripherals/Laptop/Images/302735_yoe3hs.png?tr=w-400",
    ratings: 4.9,
    delivery_time: 5,
  },
  {
    id: 26,
    category: "Laptops",
    brand: "Dell",
    model: "XPS 13",
    price: 1099,
    image: "https://example.com/images/dell-xps-13.jpg",
    ratings: 4.7,
    delivery_time: 4,
  },
  {
    id: 27,
    category: "Laptops",
    brand: "HP",
    model: "Spectre x360",
    price: 1299,
    image: "https://example.com/images/hp-spectre-x360.jpg",
    ratings: 4.6,
    delivery_time: 6,
  },
  {
    id: 28,
    category: "Laptops",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon",
    price: 1499,
    image: "https://example.com/images/lenovo-thinkpad-x1-carbon.jpg",
    ratings: 4.8,
    delivery_time: 3,
  },
  {
    id: 29,
    category: "Laptops",
    brand: "Asus",
    model: "ZenBook Duo",
    price: 1399,
    image: "https://example.com/images/asus-zenbook-duo.jpg",
    ratings: 4.5,
    delivery_time: 7,
  },
  {
    id: 30,
    category: "Laptops",
    brand: "Microsoft",
    model: "Surface Laptop 4",
    price: 1399,
    image: "https://example.com/images/microsoft-surface-laptop.jpg",
    ratings: 4.7,
    delivery_time: 4,
  },
  {
    id: 31,
    category: "Laptops",
    brand: "Acer",
    model: "Swift 3",
    price: 849,
    image: "https://example.com/images/acer-swift-3.jpg",
    ratings: 4.6,
    delivery_time: 6,
  },
  {
    id: 32,
    category: "Laptops",
    brand: "Razer",
    model: "Blade 15",
    price: 2499,
    image: "https://example.com/images/razer-blade-15.jpg",
    ratings: 4.8,
    delivery_time: 5,
  },
  {
    id: 33,
    category: "Laptops",
    brand: "HP",
    model: "Pavilion 15",
    price: 699,
    image:
      "https://img.freepik.com/free-photo/laptop-wooden-table-dark-room-with-window_1142-58872.jpg?t=st=1727616323~exp=1727619923~hmac=a48f8d06a3857a206716a249563de9f52ceb2902626d421f14a81bb796c51902&w=360",
    ratings: 4.5,
    delivery_time: 3,
  },
  {
    id: 34,
    category: "Laptops",
    brand: "Dell",
    model: "Inspiron 15",
    price: 599,
    image: "https://example.com/images/dell-inspiron-15.jpg",
    ratings: 4.4,
    delivery_time: 4,
  },
  {
    id: 35,
    category: "Laptops",
    brand: "Lenovo",
    model: "IdeaPad Flex 5",
    price: 749,
    image: "https://example.com/images/lenovo-ideapad-flex-5.jpg",
    ratings: 4.5,
    delivery_time: 3,
  },
  {
    id: 36,
    category: "Laptops",
    brand: "Asus",
    model: "VivoBook 15",
    price: 649,
    image: "https://example.com/images/asus-vivobook-15.jpg",
    ratings: 4.3,
    delivery_time: 5,
  },
  {
    id: 37,
    category: "Men's T-Shirts",
    name: "Classic White T-Shirt",
    price: 19.99,
    image:
      "https://assets.myntassets.com/f_webp,dpr_1.0,q_60,w_210,c_limit,fl_progressive/assets/images/30232946/2024/8/12/91f3bd24-5b22-45a9-bff7-ff8a7bbf25ee1723456249253-Classics-Logo-Mens-T-Shirt-5981723456248819-1.jpg",
    color: "White",
    size: ["S", "M", "L", "XL"],
    description:
      "A simple, clean, and classic white t-shirt made of 100% cotton.",
  },
  {
    id: 38,
    category: "Men's T-Shirts",
    name: "Black Crew Neck T-Shirt",
    price: 24.99,
    image:
      "https://assets.myntassets.com/f_webp,dpr_1.0,q_60,w_210,c_limit,fl_progressive/assets/images/7487209/2022/4/19/4303a3a1-0930-4f66-98a3-85406f09ac011650355012181FreeAuthorityCrewNeckBlackMenTshirt1.jpg",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    description:
      "A versatile black crew neck t-shirt that's perfect for casual wear.",
  },
  {
    id: 39,
    category: "Men's T-Shirts",
    name: "Graphic T-Shirt",
    price: 29.99,
    image:
      "https://assets.myntassets.com/f_webp,dpr_1.0,q_60,w_210,c_limit,fl_progressive/assets/images/23622024/2024/3/28/a3059c83-e102-4d11-a142-081704a28a5f1711623880504-RARE-RABBIT-Printed-Slim-Fit-Cotton-T-shirt-5821711623880405-11.jpg",
    color: "Blue",
    size: ["S", "M", "L"],
    description:
      "A stylish graphic t-shirt featuring a bold and modern design.",
  },
  {
    id: 40,
    category: "Men's T-Shirts",
    name: "Striped T-Shirt",
    price: 22.99,
    image:
      "https://assets.myntassets.com/f_webp,dpr_1.0,q_60,w_210,c_limit,fl_progressive/assets/images/12956244/2021/4/20/486a3efe-6fbe-4297-8256-a012303970621618915179262-Kook-N-Keech-Men-Tshirts-971618915178743-3.jpg",
    color: "Red",
    size: ["S", "M", "L", "XL"],
    description: "A trendy striped t-shirt, perfect for summer outings.",
  },
  {
    id: 41,
    category: "Men's T-Shirts",
    name: "V-Neck Cotton T-Shirt",
    price: 21.99,
    image:
      "https://assets.myntassets.com/f_webp,dpr_1.0,q_60,w_210,c_limit,fl_progressive/assets/images/29883084/2024/6/21/fa8756d3-928d-459b-98a3-4833197ffed31718970907862-DAMENSCH-Breeze-Ultralight-V-Neck-Solid-T-shirt-726171897090-11.jpg",
    color: "Gray",
    size: ["M", "L", "XL"],
    description:
      "Soft, lightweight v-neck t-shirt made from premium cotton fabric.",
  },
  {
    id: 42,
    category: "Men's T-Shirts",
    name: "Long Sleeve T-Shirt",
    price: 26.99,
    image:
      "https://assets.myntassets.com/f_webp,dpr_1.0,q_60,w_210,c_limit,fl_progressive/assets/images/21807308/2024/5/2/648dc303-3bfd-4d1b-96b8-0c7e0c9ca3cc1714629602516-The-Souled-Store-Men-Colourblocked-Oversize-Fit-Cotton-Overs-6.jpg",
    color: "Navy Blue",
    size: ["M", "L", "XL"],
    description: "A comfortable long-sleeve t-shirt for cooler days.",
  },
  {
    id: 43,
    category: "Men's T-Shirts",
    name: "Pocket T-Shirt",
    price: 18.99,
    image:
      "https://assets.myntassets.com/f_webp,dpr_1.0,q_60,w_210,c_limit,fl_progressive/assets/images/30256241/2024/7/17/8fb826b0-7b6b-4eac-b0ea-241141c1c27e1721212884353JackJonesMenPrintedPocketsT-shirt1.jpg",
    color: "Olive Green",
    size: ["S", "M", "L"],
    description: "A stylish t-shirt with a convenient front pocket.",
  },
  {
    id: 44,
    category: "Men's T-Shirts",
    name: "Henley T-Shirt",
    price: 27.99,
    image:
      "https://assets.myntassets.com/f_webp,dpr_1.0,q_60,w_210,c_limit,fl_progressive/assets/images/28693598/2024/4/5/e63d2b9f-38d3-4b34-8b3d-f3524b34a6b81712260534746ManiacMenStripedHenleyNeckPocketsT-shirt1.jpg",
    color: "Burgundy",
    size: ["S", "M", "L", "XL"],
    description: "A casual yet refined Henley t-shirt with button details.",
  },
  {
    id: 45,
    category: "Men's T-Shirts",
    name: "Raglan T-Shirt",
    price: 23.99,
    image:
      "https://assets.myntassets.com/f_webp,dpr_1.0,q_60,w_210,c_limit,fl_progressive/assets/images/27193510/2024/1/26/9fe1378c-7383-4ca3-b819-68dccc296f2d1706217070560CrazymonkUnisexPrintedT-shirt1.jpg",
    color: "Black & White",
    size: ["S", "M", "L"],
    description: "A sporty raglan t-shirt with contrasting sleeves.",
  },
  {
    id: 46,
    category: "Men's T-Shirts",
    name: "Muscle Fit T-Shirt",
    price: 28.99,
    image:
      "https://assets.myntassets.com/f_webp,dpr_1.0,q_60,w_210,c_limit,fl_progressive/assets/images/2024/AUGUST/27/qaUb7thG_16bb5e4db9484aabbb74c92fa176dcb1.jpg",
    color: "Charcoal",
    size: ["M", "L", "XL"],
    description: "A muscle fit t-shirt designed to showcase athletic physique.",
  },
  {
    id: 47,
    category: "Mobiles",
    brand: "Apple",
    model: "iPhone 14 Pro",
    price: 999,
    image: "https://m.media-amazon.com/images/I/61XO4bORHUL._AC_UY218_.jpg",
    ratings: 4.9,
    delivery_time: 2,
  },
  {
    id: 48,
    category: "Mobiles",
    brand: "Samsung",
    model: "Galaxy S23 Ultra",
    price: 1199,
    image: "https://m.media-amazon.com/images/I/71OXmy3NMCL._AC_UY218_.jpg",
    ratings: 4.8,
    delivery_time: 3,
  },
  {
    id: 49,
    category: "Mobiles",
    brand: "iQOO",
    model: "Z9s 5G",
    price: 699,
    image: "https://m.media-amazon.com/images/I/61nO5YRaAxL._AC_UY218_.jpg",
    ratings: 4.7,
    delivery_time: 2,
  },
  {
    id: 50,
    category: "Mobiles",
    brand: "OnePlus",
    model: "OnePlus 11",
    price: 649,
    image: "https://m.media-amazon.com/images/I/613SAOPmLeL._AC_UY218_.jpg",
    ratings: 4.6,
    delivery_time: 4,
  },
  {
    id: 51,
    category: "Mobiles",
    brand: "Xiaomi",
    model: "Mi 13 Pro",
    price: 599,
    image: "https://m.media-amazon.com/images/I/71aiqeP-APL._AC_UY218_.jpg",
    ratings: 4.5,
    delivery_time: 3,
  },
  {
    id: 52,
    category: "Mobiles",
    brand: "Sony",
    model: "Xperia 5 V",
    price: 999,
    image: "https://m.media-amazon.com/images/I/51vJuXD50lL._AC_UY218_.jpg",
    ratings: 4.7,
    delivery_time: 5,
  },
  {
    id: 53,
    category: "Mobiles",
    brand: "Oppo",
    model: "F27 Pro",
    price: 799,
    image: "https://m.media-amazon.com/images/I/91AnvgyG1sL._AC_UY218_.jpg",
    ratings: 4.6,
    delivery_time: 4,
  },
  {
    id: 54,
    category: "Mobiles",
    brand: "Vivo",
    model: "Vivo X90 Pro",
    price: 699,
    image: "https://m.media-amazon.com/images/I/71Mc1FdLrWL._AC_UY218_.jpg",
    ratings: 4.5,
    delivery_time: 3,
  },
  {
    id: 55,
    category: "Mobiles",
    brand: "Realme",
    model: "GT 2 Pro",
    price: 499,
    image: "https://m.media-amazon.com/images/I/71fhaUR7VGL._AC_UY218_.jpg",
    ratings: 4.4,
    delivery_time: 5,
  },
  {
    id: 56,
    category: "Sneakers",
    brand: "Nike",
    model: "Air Max 270",
    price: 150,
    image:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/kncr6f3jysl34ejmk7xp/NIKE+AIR+MAX+270+%28GS%29.png",
    ratings: 4.7,
    delivery_time: 3,
  },
  {
    id: 57,
    category: "Sneakers",
    brand: "Adidas",
    model: "UltraBoost 21",
    price: 180,
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/2eb4c41299344f07b18e3f6e7150c092_9366/adidas_Switch_Fwd_2_Running_Shoes_White_ID0533_06_standard.jpg",
    ratings: 4.8,
    delivery_time: 4,
  },
  {
    id: 58,
    category: "Sneakers",
    brand: "Puma",
    model: "RS-X",
    price: 110,
    image:
      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/400995/02/sv01/fnd/IND/fmt/png/RS-X-Efekt-Lights-On-Reflect-Unisex-Sneakers",
    ratings: 4.6,
    delivery_time: 5,
  },
  {
    id: 59,
    category: "Sneakers",
    brand: "Reebok",
    model: "Classic Leather",
    price: 75,
    image:
      "https://imagescdn.reebok.in/img/app/product/3/39706511-14539929.jpg?auto=format&w=390",
    ratings: 4.5,
    delivery_time: 3,
  },
  {
    id: 60,
    category: "Sneakers",
    brand: "Nike",
    model: " Air Jordan Legacy 312 Low",
    price: 175,
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/5194f597-a088-4357-85d3-8589d59b42d8/AIR+JORDAN+LEGACY+312+LOW.png",
    ratings: 4.7,
    delivery_time: 4,
  },
  {
    id: 61,
    category: "Sneakers",
    brand: "Adidas",
    model: "Ozelia Shoes",
    price: 160,
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/6ae52eeeb9f14b3cb4c1adf701470acb_9366/Ozelia_Shoes_White_GX3268_06_standard.jpg",
    ratings: 4.5,
    delivery_time: 5,
  },
  {
    id: 62,
    category: "Sneakers",
    brand: "Puma",
    model: "BMW M Motorsport N ",
    price: 55,
    image:
      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_500,h_500/global/308057/03/sv01/fnd/IND/fmt/png/BMW-M-Motorsport-Neo-Cat-2.0-Unisex-Driving-Shoes",
    ratings: 4.4,
    delivery_time: 3,
  },
  {
    id: 63,
    category: "Sneakers",
    brand: "Nike",
    model: "Air Jordan 1 Low SE",
    price: 65,
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/e4b9c2f6-9a19-475b-8f4e-3c3e9494c2df/AIR+JORDAN+1+LOW+SE.png",
    ratings: 4.6,
    delivery_time: 4,
  },
  {
    id: 64,
    category: "Sneakers",
    brand: "Sketchers",
    model: "UNO - STAND ON AIR",
    price: 140,
    image:
      "https://www.skechers.in/on/demandware.static/-/Sites-skechers_india/default/dw83845255/images/large/197627149967-4.jpg",
    ratings: 4.7,
    delivery_time: 5,
  },
  {
    id: 65,
    category: "Sneakers",
    brand: "Puma",
    model: "CA Pro Classic Unisex Sneakers",
    price: 160,
    image:
      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/380190/53/sv01/fnd/IND/fmt/png/CA-Pro-Classic-Unisex-Sneakers",
    ratings: 4.8,
    delivery_time: 3,
  },
  {
    id: 66,
    category: "Sneakers",
    brand: "Nike",
    model: "Air Jordan 5 Retro 'Lucky Green'",
    price: 70,
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/33305375-4f76-4111-b0c4-8829c7c6a133/WMNS+AIR+JORDAN+5+RETRO.png",
    ratings: 4.3,
    delivery_time: 4,
  },
  {
    id: 67,
    category: "Sneakers",
    brand: "Skechers",
    model: "D'lites",
    price: 65,
    image:
      "https://www.skechers.in/on/demandware.static/-/Sites-skechers_india/default/dw08b84c2e/images/large/196989934976-4.jpg",
    ratings: 4.5,
    delivery_time: 5,
  },
  {
    id: 68,
    brand: "Samsung",
    category: "Television",
    model: "QLED 8K",
    price: 3499,
    image: "https://example.com/images/samsung-qled-8k.jpg",
    ratings: 4.9,
    delivery_time: 7,
  },
  {
    id: 69,
    brand: "LG",
    category: "Television",
    model: "OLED C1",
    price: 2999,
    image: "https://example.com/images/lg-oled-c1.jpg",
    ratings: 4.8,
    delivery_time: 5,
  },
  {
    id: 70,
    brand: "Sony",
    category: "Television",
    model: "Bravia XR",
    price: 1999,
    image: "https://example.com/images/sony-bravia-xr.jpg",
    ratings: 4.7,
    delivery_time: 6,
  },
  {
    id: 71,
    brand: "TCL",
    category: "Television",
    model: "6-Series",
    price: 999,
    image: "https://example.com/images/tcl-6-series.jpg",
    ratings: 4.5,
    delivery_time: 4,
  },
  {
    id: 72,
    brand: "Vizio",
    category: "Television",
    model: "P-Series",
    price: 1299,
    image: "https://example.com/images/vizio-p-series.jpg",
    ratings: 4.6,
    delivery_time: 3,
  },
  {
    id: 73,
    brand: "Hisense",
    category: "Television",
    model: "ULED 4K",
    price: 799,
    image: "https://example.com/images/hisense-uled-4k.jpg",
    ratings: 4.4,
    delivery_time: 5,
  },
  {
    id: 74,
    brand: "Philips",
    category: "Television",
    model: "Ambilight",
    price: 1099,
    image: "https://example.com/images/philips-ambilight.jpg",
    ratings: 4.5,
    delivery_time: 6,
  },
  {
    id: 75,
    brand: "Panasonic",
    category: "Television",
    model: "JZ2000",
    price: 2499,
    image: "https://example.com/images/panasonic-jz2000.jpg",
    ratings: 4.7,
    delivery_time: 5,
  },
  {
    id: 76,
    brand: "Sharp",
    category: "Television",
    model: "Aquos 4K",
    price: 599,
    image: "https://example.com/images/sharp-aquos-4k.jpg",
    ratings: 4.3,
    delivery_time: 4,
  },
  {
    id: 77,
    brand: "Sanyo",
    category: "Television",
    model: "DP32D3",
    price: 249,
    image: "https://example.com/images/sanyo-dp32d3.jpg",
    ratings: 4.2,
    delivery_time: 3,
  },
  {
    id: 78,
    brand: "Insignia",
    category: "Television",
    model: "Fire TV Edition",
    price: 329,
    image: "https://example.com/images/insignia-fire-tv.jpg",
    ratings: 4.5,
    delivery_time: 4,
  },
  {
    id: 79,
    brand: "Westinghouse",
    category: "Television",
    model: "TV",
    price: 349,
    image: "https://example.com/images/westinghouse-tv.jpg",
    ratings: 4.4,
    delivery_time: 5,
  },
  {
    id: 80,
    brand: "Rolex",
    category: "Watches",
    model: "Submariner",
    price: 8500,
    image: "https://example.com/images/rolex-submariner.jpg",
    ratings: 4.9,
    delivery_time: 7,
  },
  {
    id: 81,
    brand: "Omega",
    category: "Watches",
    model: "Speedmaster",
    price: 5200,
    image: "https://example.com/images/omega-speedmaster.jpg",
    ratings: 4.8,
    delivery_time: 6,
  },
  {
    id: 82,
    brand: "Tag Heuer",
    category: "Watches",
    model: "Carrera",
    price: 3500,
    image: "https://example.com/images/tag-heuer-carrera.jpg",
    ratings: 4.7,
    delivery_time: 5,
  },
  {
    id: 83,
    brand: "Casio",
    category: "Watches",
    model: "G-Shock",
    price: 120,
    image: "https://example.com/images/casio-g-shock.jpg",
    ratings: 4.6,
    delivery_time: 4,
  },
  {
    id: 84,
    brand: "Seiko",
    category: "Watches",
    model: "5 Sports",
    price: 250,
    image: "https://example.com/images/seiko-5-sports.jpg",
    ratings: 4.5,
    delivery_time: 3,
  },
  {
    id: 85,
    brand: "Fossil",
    category: "Watches",
    model: "Hybrid HR",
    price: 199,
    image: "https://example.com/images/fossil-hybrid-hr.jpg",
    ratings: 4.4,
    delivery_time: 5,
  },
  {
    id: 86,
    brand: "Citizen",
    category: "Watches",
    model: "Eco-Drive",
    price: 350,
    image: "https://example.com/images/citizen-eco-drive.jpg",
    ratings: 4.6,
    delivery_time: 6,
  },
  {
    id: 87,
    brand: "Michael Kors",
    category: "Watches",
    model: "Gen 5",
    price: 250,
    image: "https://example.com/images/michael-kors-gen5.jpg",
    ratings: 4.5,
    delivery_time: 7,
  },
  {
    id: 88,
    brand: "Timex",
    category: "Watches",
    model: "Expedition",
    price: 55,
    image: "https://example.com/images/timex-expedition.jpg",
    ratings: 4.3,
    delivery_time: 4,
  },
  {
    id: 89,
    brand: "Tissot",
    category: "Watches",
    model: "PRX",
    price: 650,
    image: "https://example.com/images/tissot-prx.jpg",
    ratings: 4.7,
    delivery_time: 5,
  },
  {
    id: 90,
    brand: "Skagen",
    category: "Watches",
    model: "Frederik",
    price: 199,
    image: "https://example.com/images/skagen-frederik.jpg",
    ratings: 4.4,
    delivery_time: 4,
  },
  {
    id: 91,
    brand: "Hamilton",
    category: "Watches",
    model: "Khaki Field",
    price: 495,
    image: "https://example.com/images/hamilton-khaki-field.jpg",
    ratings: 4.8,
    delivery_time: 6,
  },
];
